services:
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "$POSTGRES_DB", "-U", "$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

 
  rls-django-web:
    build: .
    container_name: rls-django-docker
    entrypoint: [ "bash", "-c", "python3 manage.py migrate && gunicorn --bind 0.0.0.0:8000 --workers 3 rls.wsgi"]
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ${HOST_MEDIA_ROOT}
        target: ${DJANGO_MEDIA_ROOT}
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_MEDIA_ROOT=${DJANGO_MEDIA_ROOT}
    env_file:
      - django.env
      
volumes:
    postgres_data: