services:
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - common.env
 
  django-web:
    build: .
    container_name: rls-django-docker
    entrypoint: [ "bash", "-c", "python3 manage.py migrate && gunicorn --bind 0.0.0.0:8000 --workers 3 rls.wsgi"]
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ${HOST_MEDIA_ROOT}
        target: ${DJANGO_MEDIA_ROOT}
    depends_on:
      - db
    env_file:
      - django.env
      - common.env
      - .env
      
volumes:
    postgres_data: